spring:
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/views/


server:
  port: 8081




